DROP TABLE IF EXISTS `Product`;
DROP TABLE IF EXISTS `Taste`;
DROP TABLE IF EXISTS `Package`;
DROP TABLE IF EXISTS `Product_Taste_Package`;
DROP TABLE IF EXISTS `Composition`;
DROP TABLE IF EXISTS `Supplier`;
DROP TABLE IF EXISTS `Customer`;
DROP TABLE IF EXISTS `Discount`;
DROP TABLE IF EXISTS `Commission`;
DROP TABLE IF EXISTS `Warehouse`;
DROP TABLE IF EXISTS `Member`;
DROP TABLE IF EXISTS `StockUpdate`;
DROP TABLE IF EXISTS `TRHD`;
DROP TABLE IF EXISTS `TRDT`;
DROP TABLE IF EXISTS `User`;

